texastribune/queso-ui

assets/scss/3-resets/_all-legacy.scss, assets/scss/3-resets/_all-v2.scss, assets/scss/3-resets/_all.scss, assets/scss/4-elements/_all-legacy.scss, assets/scss/4-elements/_all.scss, assets/scss/5-typography/_all-legacy.scss, assets/scss/5-typography/_all-v2.scss, assets/scss/5-typography/_all.scss, assets/scss/6-components/_all.scss, assets/scss/7-utilities/_all-legacy.scss, assets/scss/7-utilities/_all-v2.scss, assets/scss/7-utilities/_all.scss, assets/scss/all-legacy.scss, assets/scss/all.scss, assets/scss/base-v2.scss, docs/build/build.js, docs/build/develop.js, docs/build/paths.js, docs/build/watch.js, docs/src/index.html, docs/src/js/ds.js, docs/src/page.html, docs/src/preview.html, docs/src/scss/ds.scss
These file changes are a little misleading so here are the high level changes:
New world
- Uses `assets/{{ subfolder }}/_all.scss` in each sub folder
- Uses `assets/base-v2.scss` for our "just to get you started base"*
- Uses `assets/all.scss` for our "I just want everything file"
*We'll rename this to just `base.scss` after we're done moving files around in the main repo
Old world (now always prefixed with legacy)
- Uses `assets/{{ subfolder }}/_all-legacy.scss` in each sub folder
- Doesn't have a "just to get you started base"
- Uses `assets/all-legacy.scss` for our "I just want everything _from legacy_ file "
I also added an ability to streamline your view in the docs to filter out the legacy that I find myself needing less and less. One day I think we just stop displaying docs from …
=> Adjust naming conventions to better suit our needs and add legacy toggle

.pre-commit-config.yaml, README.md, assets/scss/5-typography/_t-size.scss, assets/scss/5-typography/_typography-v2.scss, assets/scss/6-components/card/card.html, assets/scss/7-utilities/_color-helpers.scss, assets/scss/7-utilities/_display.scss, assets/scss/7-utilities/_layout-v2.scss, assets/scss/7-utilities/_layout.scss, assets/scss/7-utilities/_spacing.scss, docs/build/docs.js, docs/src/index.html, docs/src/js/ds.js, docs/src/macros/snippet.html, docs/src/page.html, docs/src/preview.html, docs/src/scss/ds.scss, package.json, tasks/style-doc.js, yarn.lock
- Adds linting
- Introduces helper class `{{isHelper}}` to hide previews for helper/non BEM naming conventions
- And just some general cleanup...
- Creates raw previews for non components
- Removes float classes
- Removes old podcast card prototypes
- Adds better title text
- Defaults the view to hide legacy styles
- Moves display classes into _display
=> Linting, helper indicator, and cleanup

package.json, yarn.lock
This changes lots of packages from devDependencies => dependencies
We do this so that our /task scripts will successfully run when used in the wild.
=> Add required packages to dependencies

assets/scss/6-components/full-page-loader/_full-page-loader.scss, assets/scss/6-components/info-list/_info-list.scss, assets/scss/6-components/table/table.html
+ Adds missing `list-style:none;` to `.c-info-list`
+ Forces `th` elements to align left
+ Revamps `.c-full-page-loader` to make it a simple translucent overlay that can in turn contain other stuff, including our `.c-loading` component
=> A few small things

docs/build/build.js, docs/build/docs.js, docs/build/paths.js, docs/build/watch.js, docs/src/index.html, docs/src/page.html, docs/src/preview.html, tasks/styles.js, tasks/utils.js
High level overview of what happens to SCSS on build now:
1. All the same compiling as before (only with level 2 CSS cleaning 😱 )
2. Instead of `mystyles.css`, a name of `mystyles + Date.now() + .css` will output into the specified out directory
3. In order to use that file, we need an automatic output of the raw name and revved name. For that, we now pass a map location (`mappedStylesManifest`) in `styles.js` to specify where the following map should output:
```json
{
"ds": "ds.1557765106956.css",
"all": "all.1557765106961.css",
"all-legacy": "all-legacy.1557765107018.css"
}
```
4. We only update the date string if the file is different from before.
=> Reconfigure styles.js to add file revving to outputted CSS + a map of those names

assets/scss/6-components/info-list/_info-list.scss, assets/scss/6-components/info-list/info-list.html
Use grid instead of flexbox to better accommodate multiple rows of items.
=> Better .c-info-list

assets/scss/6-components/site-footer/_site-footer.scss, assets/scss/6-components/site-footer/site-footer.html, assets/scss/utilities/_notch.scss
Refactors the site-footer component in various ways:
+ Replaces lots of component-specific styles with helper classes
+ Makes the HTML example more generic (i.e. not specific to tt.org)
+ Also removes the margin that's baked into `has-notch--*` so that it can be applied via a helper class (including in the site footer)
@ashley-hebler This of course will require HTML updates in `texastribune`. So your call whether you want to hold off merging this for a bit, or if you want to merge this but just not update the commit hash in `texastribune`'s `yarn.lock`.
=> Improve .c-site-footer styles

assets/scss/6-components/navbar/_navbar.scss, assets/scss/6-components/navbar/navbar.html
This is very similar to my site-footer PR: bringing our helper class/BEM world to a legacy component. Some notes:
+ There are two variations of the nav now: dark and light. Changing `.c-navbar--dark` to `.c-navbar--light` accomplishes that (along with subbing in the proper Trib logo)
+ You might be thinking, "Why didn't he just use our background- and text-color helpers to accomplish the dark/light difference?" The reason is because it's not that simple. For example, the hover animations on link pseudo elements also change depending on the theme. So I felt this is a scenario where fewer helper classes and true BEM made this code easier to read and manage.
+ I updated the HTML example to be more generic (the existing one was for the home-page nav, which is pretty customized compared to our …
=> Improve .c-navbar styles

assets/scss/2-tools/_functions.scss, assets/scss/5-typography/_t-size.scss, assets/scss/7-layout/_container.scss, assets/scss/7-layout/_grid.scss, assets/scss/7-layout/container.html, assets/scss/utilities/_spacing.scss, docs/src/js/ds.js
- Changes l-container to a rem value. I think changing the variable values directly comes later after we switch to 62.5%.
- Injects size variable values for the `t-size-<size>`, `l-container-<size>`, and `has-<size>-btm-marg` into our docs with some hackyish JS. I wanted a quick way to peek at the calculated values. (I think designers communicate in pixels too, so I was thinking it might aid in translation of design feedback.)
=> Convert l-container to rems and add display sizes

assets/scss/1-settings/_measures.scss, assets/scss/6-components/site-footer/_site-footer.scss, assets/scss/6-components/site-footer/site-footer.html, assets/scss/7-layout/container.html, assets/scss/utilities/_spacing.scss, docs/src/js/ds.js
I've been missing that [`grid_separator--xs`](https://github.com/texastribune/ds-toolbox/blob/master/assets/scss/7-layout/_grid-legacy.scss#L148-L158) from old world. I've been trying to account for teeny tiny margin-bottoms with line-height, but that was silly [as you saw](https://github.com/texastribune/donations/pull/224#issuecomment-499268469). 
I like how the new world version stays true to our size map in keeping the class names tied to our map labels and respective rem values.
I don't think this tiny unit will be needed in anything other than margins - aka def not needed for text. Creating a new margin-map as an extension of our size-map will allow us to lessen the impact of adding one more size and give us that flexibility of teeny tiny spacers.
FWIW `grid_separator--xs` is used …
=> Add even smaller option for has-<size>-btm-marg

assets/scss/utilities/_color-helpers.scss, docs/build/build.js, docs/build/watch.js, package.json, yarn.lock
Steps to queso-ifying our front-end:
1. **Convert _ds-toolbox_ compiling tasks to queso-tools** <= we are here
2. Convert _donations_ compiling tasks to queso-tools
3. Deprecate styles.js and icons.js and related dependencies in _ds-toolbox_
4. Restructure _ds-toolbox_ to form queso-ui package (leaving assets folder intact)
5. Convert _donations_ asset grab to queso-ui
5. Convert _texastribune_ asset grab to queso-ui
=> Convert internal compiling tasks to queso-tools

assets/scss/1-settings/_measures.scss, assets/scss/4-elements/_all.scss, assets/scss/6-components/_all.scss, assets/scss/6-components/button/_button.scss, assets/scss/6-components/button/button.html, assets/scss/6-components/caption/_caption.scss, assets/scss/6-components/caption/caption.html, assets/scss/6-components/share/_share.scss, assets/scss/6-components/share/share.html, assets/scss/6-components/story-body/_story-body.scss, assets/scss/6-components/story-body/story-body.html, assets/scss/7-layout/_align.scss, assets/scss/7-layout/align.html, assets/scss/utilities/_color-helpers.scss, assets/scss/utilities/_spacing.scss, docs/src/preview-raw.html
Preview with:
`yarn dev-docs`
**globals added**
- `figure` and `blockquote` - remove default margin/padding
- `hr` - Typically the default for hr borders is `border-style: inset`. That is silly. Solid and our own gray variable FTW.
**utilities classes added:**
- `has-reset-padding` - I ended up needing the `c-button` class without any padding. This reset felt more versatile than a reset scoped to c-button.
- _color helpers_
- `has-text-facebook`|`has-bg-facebook`|`has-text-hover-facebook`
- `has-text-twitter`|`has-bg-twitter`|`has-text-hover-twitter`
- I went back and forth on this one, but I think in those few places we're we add the social colors, we'd end up with almost 6 new declarations anyhow. This also made the `c-button--outline` approach possible.
**layout classes added:**
- …
=> Add some components for story pages

assets/scss/6-components/info-drop/_info-drop.scss
Removes this extra arrow Chrome injects
=> Remove webkit arrow on c-info-drop

assets/scss/6-components/story-body/_story-body.scss, assets/scss/6-components/story-body/story-body.html
The sponsor content designs introduce an `<hr>` element. While we're at it, we might as well establish that as a tool for reporters and editors to use in the story body component. Not much is needed to do this, but I added some opinionated margin top/bottom because it seems like if they ever do use those, they'd want some separation to come with it.
=> Account for hr in story body

assets/scss/6-components/button/_button.scss, assets/scss/6-components/story-body/_story-body.scss, assets/scss/7-layout/_grid-legacy.scss, assets/scss/7-layout/_grid.scss, assets/scss/utilities/_hidden.scss, assets/scss/utilities/_spacing.scss, package.json
A step toward grid cleanup
- has-gutter-padding
- has-temp-gutter-padding
- has-section-padding
- grid_padded
- grid_padded--temp 
- grid_padded--{size} (5)
- hide_{from || until}--{size} (10)
Reduction in CSS (a whole 1.73kb, but still ¯\_(ツ)_/¯ ) :
- Trims down logic for adding gutter padding at various breakpoints. We seldom use grid_padded--{size} and those have a [superfluous media query](https://github.com/texastribune/queso-ui/blob/master/assets/scss/7-layout/_grid-legacy.scss#L326-L328). 
- Removes the dynamic hide helpers, which we've already replaced thanks to @AndrewGibson27.
- Removes sidebar column. This has no replacement yet, but we'll tackle that when it comes up during homepage CSS refactor.
`yarn dev`
1. See: [has-padding](http://localhost:3000/pages/utilities/has-padding …
=> Round of grid cleanup

assets/scss/1-settings/_fonts.scss, assets/scss/4-elements/_all.scss, assets/scss/5-typography/_t-helpers.scss, assets/scss/6-components/story-body/_story-body.scss, assets/scss/6-components/story-body/story-body.html
- t-space-base
- t-space-nospace
This adds text formatting updates in story body and globally.
- Adds [default line-height to p tags](https://github.com/texastribune/queso-ui/blob/text-formatting/assets/scss/4-elements/_all.scss#L58-L61) and [converts line-heights to SASS variables](https://github.com/texastribune/queso-ui/blob/text-formatting/assets/scss/6-components/story-body/_story-body.scss#L31-L36)
- Removes reliance on story body helper classes and [scopes font rules to direct decedents of c-story-body instead](https://github.com/texastribune/queso-ui/blob/text-formatting/assets/scss/6-components/story-body/_story-body.scss#L31-L36). Add base line height on paragraphs to avoid constantly setting. We do this to keep plugin styles intact.
`yarn dev`
See: [line-height …
=> Add base line height on paragraphs to avoid constantly setting

assets/scss/6-components/_all.scss, assets/scss/6-components/button/_button.scss, assets/scss/6-components/checkbox/_checkbox.scss, assets/scss/6-components/checkbox/checkbox.html, assets/scss/6-components/mini-form/_mini-form.scss, assets/scss/6-components/mini-form/mini-form.html, assets/scss/6-components/text-input/_text-input.scss, assets/scss/6-components/text-input/text-input.html, docs/config/tasks/docs.js
+ Adds components for text inputs, checkboxes, mini-form
+ Adds reduced opacity to all buttons in disabled state
- `.c-text-input`
- `.c-checkbox`
- `.c-mini-form`
These are needed for UMP, but they'll come in handy in many other places as well.
+ `yarn dev`
+ http://localhost:3000/pages/components/index.html#checkbox-c-checkbox
+ http://localhost:3000/pages/components/index.html#mini-form-c-mini-form
+ http://localhost:3000/pages/components/index.html#text-input-c-text-input
Nothing breaking. Will create pre-release on master once this is merged.
=> Add some form components

assets/scss/6-components/button/_button.scss, assets/scss/6-components/info-list/_info-list.scss, assets/scss/6-components/text-input/_text-input.scss
+ Removes iOS rounded button corners
+ Hides built in text-input X button on IE/Edge
+ Adds missing `grid-gap` on `c-info-list`
=> Small fixes

assets/scss/1-settings/_colors.scss, assets/scss/6-components/button/_button.scss
+ Adds `$color-success` (approved by Emily A.)
+ Makes it so disabled buttons do not have `cursor: pointer`
A success color feels like something we'll need in more places than just UMP. And I like having the default cursor on disabled buttons because it's a further indication you can't click it.
I'll create v2.4.0.
=> Success color and disabled-button fix

assets/scss/6-components/back-to-top/_back-to-top.scss, assets/scss/6-components/back-to-top/back-to-top.html, assets/scss/6-components/card/_card.scss, assets/scss/6-components/card/card.html, assets/scss/7-layout/_width.scss, assets/scss/utilities/_color-helpers.scss, docs/src/scss/ds.scss
- Addresses back-to-top bug on in Safari. (Safari does not like inline-block + position: sticky 😢 )
- Adds missing `$color-sponsor` `$color-twitter` `$color-facebook` to color helpers
- I noticed the components page display was taking forever waiting on the Spreaker width in the podcast card, so I removed it. Also I updated some of the placeholder text to be more generic.
Gets the back to top displaying more consistently and provides for better documentation of a few components.
`yarn dev`
See: [Most of the updates happen in components](http://localhost:3000/pages/components/#back-to-top-c-back-to-top)
No, I consider this a patch and will call it `v2.4.2`
=> Fix back-2-top on Safari; remove hanging spreaker widget; add color docs

assets/scss/7-layout/_all.scss, assets/scss/7-layout/_content-grid.scss, assets/scss/7-layout/content-grid.html
Adds a layout class to establish a simple two column grid.
- l-content-grid
As I was reorganizing the sass files in in the custom grid I added for [The Blast](https://www.texastribune.org/theblast/), it occurred to me that it might be better served as a global component.
Some potential future implementations of this
- The homepage
- The about page
- UMP
`yarn dev`
See: [l-content-grid](http://localhost:3000/pages/layout/l-content-grid/raw-preview.html)
No just a minor release.
=> Add a content grid layout

assets/scss/6-components/checkbox/_checkbox.scss
Allows the first column of the checkbox grid to fill the space it needs. I don't know why I didn't do this to start.
More safe across browsers. They all style checkboxes a little bit differently, so let's ensure we never have any overflow.
Will create 2.5.1.
=> Fix checkbox grid

assets/scss/6-components/checkbox/_checkbox.scss, assets/scss/6-components/checkbox/checkbox.html, assets/scss/6-components/mini-form/_mini-form.scss, assets/scss/6-components/mini-form/mini-form.html, assets/scss/6-components/text-input/_text-input.scss, assets/scss/6-components/text-input/text-input.html
+ Make it so, instead of `c-text-input` living on the input itself, it lives on the `div` surrounding the input. This is for consistency with `c-checkbox` and, I think, makes more sense: The component isn't just the input -- it's the input, the label and any error messages.
+ Adds invalid-state functionality to `c-checkbox`
- `c-text-input__input`
- `c-checkbox__inputs`
Just figurin' out this form stuff as I go.
This is indeed breaking! But it will only break things in UMP read/write, which isn't live yet. I'll update it.
=> A few form updates

package.json, yarn.lock
Updates to new version of `queso-tools`.
I added a small update to `queso-tools` that specifies where compiling fails. We lost that feature when I switched to `node-sass`, which is my mistake 😬 
Nope and I don't think it event merits a release
=> Add new version of queso-tools for compiling error reporting

assets/scss/4-elements/_all.scss, assets/scss/7-layout/_all.scss, assets/scss/7-layout/_col-grid.scss, assets/scss/7-layout/col-grid.html, docs/src/scss/ds.scss
Adds a grid helper more global line-heights.
- l-col-grid
- l-col-grid--1x3
- l-col-grid--xxxs-gap
- l-col-grid--resp
l-col-grid - This is essentially the photo grid styles, but a little more generalized. We [talked about](https://github.com/texastribune/texastribune/pull/3629#issuecomment-526269751) how that one is implemented in the story page style swap PR. 
All `figcaption` and `ul` tags' line-height will be our base line-height - Hopefully this adds consistency and saves us from keep having to set it with our `t-space-base` helper.
`yarn dev`
See: [`l-col-grid`](http://localhost:3000/pages/layout/index.html#column-grid-l-col-grid)
The footer links on queso templates will get a little more spaced out with the line-height, but that feels too trivial to me to deem it "_breaking_." I'd …
=> Add first attempt at grid helper and global updates 

assets/scss/6-components/navbar/_navbar.scss
Removes texastribune repo-specfic nav styles
Removes unused CSS in portal
`yarn dev`
See: [navbar](http://localhost:3000/pages/components/c-navbar/raw-preview.html)
I don't think so, but @AndrewGibson27, I'll pre-release and test in donations.
=> Port tt-specfic nav styles over to tt repo

assets/scss/6-components/cta-block/_cta-block.scss, assets/scss/6-components/cta-block/cta-block.html
Style fixes for cta plugins.
After seeing it in context of a story, we needed to add some adjustments.
`yarn dev`
See: [cta-block](http://localhost:3000/pages/components/index.html#cta-block-c-cta-block)
It's mostly just changes to the demo, but I also needed some component-level update. Let's call this a patch
=> CTA plugin updates

assets/scss/5-typography/_font-families.scss
Adds `font-display: swap` to our fonts
Lighthouse suggests it and there's an unexplained uptick in our visually complete metric. I thought font-face observer made this property obsolete, but maybe it has a slight benefit. This also hurts 0%.
Just a patch
=> Add swap for lighthouse and perhaps viz complete?

assets/scss/6-components/navbar/_navbar.scss, assets/scss/6-components/navbar/navbar.html, package.json
Simplifies spacing classes on the navigation. Instead of having to put `--space-right` or `--giant-space-right` on stuff, those margins are now baked in with some available overrides and `:last-child` rules. This simplifies the markup greatly. One of the main reasons we needed the more verbose modifiers was because we didn't have access to React fragments in our `texastribune` navigation. Now, we do.
Also allows for two slightly-spaced rows of items in the mobile dropdown (to distinguish between regular links and action links like "log out").
- Modifies some existing ones
- `c-navbar-item--giant-space-right`
- `c-navbar-item--space-right`
Cleaner CSS.
+ `yarn dev`
+ See navbar example and ensure it looks OK.
I'll create a major release for this (after a few test pre-releases) since it'll …
=> Simplify nav spacing

assets/scss/6-components/back-to-top/_back-to-top.scss, assets/scss/utilities/_hidden.scss
Back to top button fix
The back to top button on the donor wall needs some breathing room.
Nope
=> Handle fade logic in is-transparent and give back-to-top breathing room

assets/scss/no-resets.scss, docs/config/tasks/docs.js, docs/src/macros/snippet.html, docs/src/page.html, docs/src/preview-raw.html
Adds a new link to pruned CSS for individual components and helpers.
Sometimes we don't want to import the whole system, but we just want the styles. Example: Ad native ad which is served from an iframe (which doesn't inherit parent CSS)
The CSS generated in the prune CSS step only includes classes referenced in the HTML and does not include normalize.
`yarn dev`
See new CSS button
Doesn't even require a release. Docs change only.
=> Add pruned CSS view for one-off projects (native ads in this case)

assets/scss/6-components/story-body/_story-body.scss, assets/scss/6-components/story-body/story-body.html
Styles `ol`s with proper fonts, links, margins.
The people need to order lists!
`yarn dev`
See: [c-story-body](http://localhost:3000/pages/components/c-story-body/raw-preview.html)
Net add. I'll add this as a patch, because I'd call this an oversight of mine in the first place.
=> Allow ordered lists in story body

assets/scss/5-typography/_font-families.scss
- Adds a missing `font-display: swap`. Not sure how I missed that the first time around.
- Removes Open Sans italic and Open Sans italic-bold
- The swap is just because we use it on the others.
- Removing those italics of Open Sans is because I don't think we actually ever use them.
The case for leaving them there 🤔 
I could also be convinced to leave those two declarations because it's my understanding that technically that font is never downloaded anyway. Since the CSS never calls for that combo of `font-family: Open Sans` and `font-style: italic`, the browser never reaches the point of requesting the file. I think this because of [bullet under #4 here](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization#the_default_behavior): 
> …
=> Remove unused fonts

assets/scss/6-components/info-drop/_info-drop.scss, assets/scss/6-components/sponsor-block/_sponsor-block.scss, assets/scss/6-components/sponsor-block/sponsor-block.html
- Shrinks down images/fonts in the sponsor ads
- Sticks `c-info-drop` to top
We had to add some changes to make the sponsor block less prominent. This is all carried into Google Ad Manager, but I'm updating here as well to keep us up to date in our docs.
The info bar `position: sticky` request stemmed from the same goal of being transparent about paid posts. We want to make sure users don't bypass it and confuse our brand with another.
Nope
=> Add feedback from paid-posts

assets/scss/2-tools/_mixins.scss, assets/scss/6-components/block-grid/_block-grid.scss, assets/scss/6-components/cta-block/_cta-block.scss, assets/scss/6-components/event-block/_event-block.scss, assets/scss/6-components/event-block/event-block.html, package.json
- Adds mixins for row and column gaps
- Increases row gap in `c-block-grid`
- Increases min column width in `c-block-grid`
- Increases gradient darkness in `c-event-block`
- Decreases space between text and buttons in `c-cta-block`
These are all things we talked about on 10/31 related to the rug/drawer
This will be `6.0.3`. No markup changes required.
@ashley-hebler LMK if the increases min column width in `c-block-grid` will throw off the home-page work you're doing. Also, here are screen grabs of the two plugins using `c-cta-block`, now with decreased button top margin. IMO it looks fine but LMK if you feel otherwise.
=> Small tweaks to event and CTA blocks

assets/scss/6-components/_all.scss, assets/scss/6-components/ad-fluid/_ad-fluid.scss, assets/scss/6-components/ad-fluid/ad-fluid.html, assets/scss/6-components/sponsor-block/_sponsor-block.scss, assets/scss/6-components/sponsor-block/sponsor-block.html
Adds some 🗜clamping to dynamic text blocks in the sponsor block component and a height wrapper to use on the /texastribune side of this ad implementation.
- c-ad-fluid
Lazy ads work best with predictable height. This allows the native ad implementation to have that predictability despite also needing variable lengths of text.
`yarn dev`
See:
- [c-ad-fluid](http://localhost:3000/pages/components/c-ad-fluid/raw-preview.html)
- [c-sponsor-block](http://localhost:3000/pages/components/c-sponsor-block/raw-preview.html)
Not really, but it does require manually updating the [native ad code] here(https://admanager.google.com/5805113#creatives/custom_native_style/detail/styleid=259910).
=> Prep sponsor content block for livin' in lazy world

assets/scss/6-components/block-grid/_block-grid.scss, assets/scss/6-components/event-block/_event-block.scss, assets/scss/6-components/event-block/event-block.html, assets/scss/7-layout/_align.scss, assets/scss/7-layout/align.html
Adds helper to align event block buttons.
-  l-align-end-self 
Less visually disruptive when event titles have varying lines of text
`yarn dev`
See: [c-event-block](http://localhost:3000/pages/components/c-event-block/raw-preview.html)
Should not.
=> Align event block buttons to bottom of container and cta spacing fixes

package.json, yarn.lock
Bumps up to the latest queso-tools dependency and logging updates
Just keeps our dependencies from falling behind.
`yarn`
`yarn dev`
**This only pertains to the build; no release needed**
=> Update queso-tools to latest release

docs/config/tasks/style-doc.js, docs/src/macros/color-swatch.html, docs/src/page.html, docs/src/scss/ds.scss, package.json, yarn.lock
Adds a little visual to aid in discussing color contrast ratios
Quick checks on colors
`yarn dev`
See: [Swatch set - Branding](http://localhost:3000/pages/settings/index.html#swatch-set-branding)
Nope, just a docs enhancement
=> Add color swatch contrast display

assets/scss/5-typography/_byline.scss, assets/scss/5-typography/byline.html, assets/scss/6-components/ad-fluid/_ad-fluid.scss, assets/scss/6-components/ad-fluid/ad-fluid.html, assets/scss/6-components/button/_button.scss, assets/scss/6-components/cta-block/_cta-block.scss, assets/scss/6-components/cta-block/cta-block.html, assets/scss/6-components/event-block/event-block.html, assets/scss/6-components/widget/_widget.scss, assets/scss/6-components/widget/widget.html, assets/scss/utilities/_all.scss, assets/scss/utilities/_border.scss, assets/scss/utilities/_rounded.scss
- Introduces some border helpers
- (Maybe?) simplifies all the CTA button variations
- Changes `t-byline` to use margin
- Makes `t-byline` example gray text meet the contrast ratio for AA
- has-border
- has-styled-border
- is-rounded-b
- is-rounded-l
- c-button--round
- Also removes some declarations that the new helpers can accommodate instead.
----
Give us the ability to create "the box" look on the fly.
Margin instead of padding allows the rug author feed to use the `t-byline` helper in this version of a byline with underlined links
I thought this might make those modifiers a little more DRY (in terms of the CSS) and systematic. What do you think @AndrewGibson27? 
To highlight that change...
instead of:
```scss
&__btns {
@include gap($size-xxs);
display: grid;
grid-auto-rows: …
```
=> Add new border helpers + CTA button layout & t-byline updates

assets/scss/6-components/story-block/_story-block.scss, assets/scss/6-components/story-block/story-block-alt.html, assets/scss/6-components/story-block/story-block.html
- Forces the `<article>` label (the h3) to be first in the markup sequence and adjusts the CSS accordingly to have the image still display first on the page render.
- Removes tabbing on the extra image link
- This guy [says to](https://css-tricks.com/how-to-section-your-html/#custom-header-id-6). It does make sense that the source order should match the hierarchy of the component.
THEN AGAIN 😩 - This bit from the [WCAG explanation](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-sequence.html) makes me question if this actually affects meaning and thus still applies here.
> Providing a particular linear order is only required where it affects meaning.
- The tabbing is a judgment call of mine based on how that story block will ultimately be repeated over and over. …
=> Revist the story block a11y implementation

assets/scss/1-settings/_colors.scss
Changes hex code of teal
Adds more contrast to teal on white text display 
`yarn dev`
[Look at that teal passing now ✅ ](http://localhost:3000/pages/settings/index.html#swatch-set-branding) 🎉 
Kinda? Not really. I'll make it a major to be on the safe side.
I'll lump it into this one https://github.com/texastribune/texastribune/pull/3744
=> New teal, who dis?

assets/scss/6-components/story-body/_story-body.scss, assets/scss/6-components/story-body/story-body.html
What the title says.
I modified one rule: `.c-story-body h3` became `.c-story-body > h2`.
So we don't skip heading levels in the `<article>`. And so in-plugin headers don't errantly pick up these styles.
This change is non-breaking inside queso because no markup changes are required. There will be an accompanying `texastribune` PR that makes our editor use `h2` tags.
=> Use h2 tags for in-story headers

assets/scss/6-components/cta-block/_cta-block.scss, assets/scss/6-components/cta-block/cta-block.html, assets/scss/6-components/event-block/event-block.html
Satisfies design request of bottom button alignment here:
but not here:
The call to action plugins look weird with bottom alignment for the buttons.
Goes with https://github.com/texastribune/texastribune/pull/3756/files
This is breaking-ish but since it's so subtle, I'll just call this a patch.
=> Add centering back to cta-block but not for event-block

package.json, yarn.lock
Switched deployment pipeline from surge to github page.
GitHub pages is more packaged up with the repo itself. Surge was always a temporary home for the assets. The package that does this was [recommended in the Nuxt.js docs](https://nuxtjs.org/faq/github-pages/#command-line-deployment)
`yarn deploy`
See: [Github page](https://texastribune.github.io/queso-ui/)
Nope just a docs update.
=> Deploy to github pages instead of surge

.github/workflows/main.yml
Uses GitHub [actions tools](https://github.com/marketplace/actions/deploy-to-github-pages) to auto push the `docs/dist` folder to the branch `gh-pages`
We won't have to manually deploy the docs. This actions helper is referenced in [this article](https://dev.to/pierresaid/deploy-node-projects-to-github-pages-with-github-actions-4jco).
N/A just does its thing when you push to master
=> Fix deployment in actions workflow

assets/scss/6-components/podcast-block/_podcast-block.scss, assets/scss/6-components/podcast-block/podcast-block.html
Reorders the podcast block so that we start with a heading tag
Better order for screenreaders
`yarn dev`
See: [c-podcast-block](http://localhost:3000/pages/components/c-podcast-block/raw-preview.html/)
Just a patch - this component isn't actually used yet.
=> Add a11y fixes to podcast-block

assets/scss/5-typography/_font-families.scss, assets/scss/6-components/story-body/story-body.html
Adds Open Sans Bold Italic back for pullquotes
I thought this font never appeared, but it does in this rare use case. It won't actually fetch the font unless a pullquote is present
Nope, just a patch
=> Add open sans bold italic back for pullquotes

assets/scss/1-settings/_measures.scss, assets/scss/2-tools/_mixins.scss, assets/scss/3-resets/_all.scss, assets/scss/4-elements/_all.scss, assets/scss/6-components/button/_button.scss, assets/scss/6-components/button/button.html, assets/scss/6-components/mini-form/_mini-form.scss, assets/scss/6-components/navbar/_navbar.scss, assets/scss/utilities/_color-helpers.scss, package-lock.json, package.json
- Adds a new skip to content link button style
- Adds links/buttons focus states
- Trims down our CSS reset (normalize -> modern-normalize)
- Fixes "Reset Password" text color in donation repo (this lost its color inheritance when I altered the hover styles mixin I think)
- c-button--skip
- :focus states added to some has-bg helpers
- Better a11y
- Normalize has some extra legacy styles we don't need. I also appreciate that this normalize version has a goal of [eventually going away](https://github.com/sindresorhus/modern-normalize/issues/2)
`npm run dev`
Test out tabbing on [buttons](http://localhost:3000/pages/components/c-button/raw-preview.html), [links](http://localhost:3000/pages/typography/t-%3Clink-style%3E/raw-preview.html), …
=> Add keyboard navigation enhancements

assets/scss/4-elements/_all.scss, assets/scss/6-components/button/_button.scss, assets/scss/utilities/_color-helpers.scss
Dials back some of the previously added focus states.
When I tested the new focus states in the main /texastribune repo, they were a little confusing. I think just relying on the outline is good for now, but will check with Art.
Another pre-release.
=> Remove custom button focus - keep :focus simple for now

assets/scss/1-settings/_colors.scss, assets/scss/2-tools/_mixins.scss, assets/scss/4-elements/_all.scss
Removes mouse click focus state.
We don't want our dotted outlines for mouse users
`yarn dev`
See: [any page](http://localhost:3000/)
Tab around and click around. You should see link outlines on tabs, but not clicks
Another pre-release of v9
=> Prevent mouse click focus state

assets/scss/3-resets/_all.scss, docs/config/paths.js, docs/src/includes/header.html, docs/src/index.html, docs/src/page.html
- Stops referencing legacy styles in docs
- Removes visible focus state of mouse click in firefox
Just a weird browser quirk
`yarn dev`
See: [index](http://localhost:3000/)
Another pre
=> Remove outline on click in firefox/legacy styles in docs

assets/scss/3-resets/_all.scss, assets/scss/4-elements/_all.scss, package-lock.json, package.json
- Removes focus states
- Brings back old normalize
I've been doing some thinking about the next major release and I want to save v9 for the color overhaul. We need to rename a bunch of color helpers and make the system more configurable for propublica apps/data-visuals-create
- For that reason, I'm reverting to _normal_ normalize to be able to just make this another minor release; let's save something that global for v9
- There's a blip of our dotted outlines we set for focus state as the page loads and I'm just not ready to introduce that. Seems like another good candidate for v9
`npm run dev`
See: [your-link](http://localhost:3000/)
This will allow us to officially release 8.4
=> Undo major changes for minor release features

assets/scss/6-components/story-body/_story-body.scss, assets/scss/6-components/story-body/story-body.html
Adds a new CSS variable to `c-story-body` for easier overrides. Also adds a modifier, which makes use of that.
- c-story-body--nested
I realized that assuming you always want story body children to have mobile padding is a bit restricting. Example: this callout plugin:
It would be better if the text was flush
`npm run dev`
See: [c-story-body](http://localhost:3000/pages/components/index.html#story-body-c-story-body)
Just a minor release
=> Add story body modifier for nested plugins

assets/scss/6-components/topic-bar/_topic-bar.scss, assets/scss/6-components/topic-bar/topic-bar.html
Makes the topic bar mobile friendly, sans-serif-y and sticky
Just some modifiers on `.c-topic-bar`.
Mobile is where it's at
`npm run dev` and check out `.c-topic-bar`
Minor release to come.
=> Update .c-topic bar

assets/scss/3-resets/_all.scss, assets/scss/6-components/site-footer/_site-footer.scss, assets/scss/6-components/site-footer/site-footer.html
- Addresses a bug I found when trying to add v9 to other repos. (That's what I get for not pre-releasing!)
- Also just a little revisit of the footer docs
- `.c-site-footer__inner ` got some default display and spacing.
With the way I had that Sass import for modern-normalize set up, it directly added it as an import instead of outputting the content of that CSS file when compiled out. We don't want that.
I noticed the headings on our footer examples deviated a little from how we usually display them and I feel like since we're always adding a grid might as well include that, but still keep the count general. Open to feedback there - not a huge deal either way!
`npm run dev`
See: [footer](http://localhost:8080/sections/components/c-site-footer/)
Patch
=> Fix modern-normalize import and update footer example

assets/scss/6-components/caption/_caption.scss, assets/scss/6-components/caption/caption.html, assets/scss/7-layout/_all.scss, assets/scss/7-layout/_position.scss, assets/scss/7-layout/position.html
Adds a few helpers for setting `position:` and a variation for captions (to be used on [full-width desktop photos](https://test.texastribune.org/2019/12/12/trumps-immigration-policies-have-slowed-migrants-central-america/))
- l-pos-rel
- l-pos-abs
- c-caption--overlay-from-bp-l
I think we need some combo of position relative and/or absolute enough that they're deserving of their own helper. I did struggle as to whether they would be a utility class or layout.
`npm run dev`
See: [The new position helpers](http://localhost:8080/sections/layout/l-pos-setting/)
**Questions:** Are these names intuitive? Do they belong in layouts or would you more naturally look in utilities for this?
See: [Captions - .c-caption--overlay-from-bp-l](http://localhost:8080/sections/components/c-caption/) …
=> Add new position helpers + caption variation

docs/config/tasks/copy.js, docs/config/tasks/github.js, package-lock.json, package.json
Switches to airbnb-base for eslint (instead of plain ol' airbnb, which includes peer-dependencies we don't need like React.)
Drop glob-watcher which is just a leftover from pre-11ty
Fewer dependencies to keep track of. Hopefully fewer dependabot PRs, but I doubt it.
`npm run build`
`npm run dev`
Make sure they both work
This is just for linting
=> Remove unnecessary dependencies

assets/scss/6-components/story-body/_story-body.scss, assets/scss/6-components/story-body/story-body.html
- Adds more heading rules
- Adds better support for `<sub>` and `<sup>`
- Cleans up `.c-story-body` docs
- .c-story-body > more heading tag rules
- .c-story-body > sub, sup (removed rules)
- .c-story-body--nested - That was for a plugin that never came to be.
- This is for the new heading tags we'll be seeing in the CMS soon
- I'm not sure why `sub, sup {position: initial;}` was there. Seems like we'd want to be able to use those how they were intended. We use seem to wrap [correction text](https://www.texastribune.org/2020/06/15/texas-coronavirus-cases-increase/) with `sup`, but having the [normalize top, bottom position rules kick in](https://github.com/sindresorhus/modern-normalize/blob/master/modern-normalize.css#L128-L147), doesn't seem to negatively affect anything where I see it …
=> Establish more text rules in story body  

assets/scss/1-settings/_colors.scss, docs/src/colors.njk, docs/src/scss/queso-docs.scss
Adds a new color variables and re-categorizes some of the ones we have 
(sorry these names are probably awful)
- `$color-white-off-light ` - For the ad placeholder
- `$color-ad-text ` - For the Become a member text
- A whole bunch of data viz color vars
It made sense to make our [ad](https://github.com/texastribune/texastribune/blob/master/frontend/sass/legacy/_ads.scss#L6) [color](https://github.com/texastribune/texastribune/blob/master/frontend/sass/legacy/_ads.scss#L26-L28) rules variables so that we could use them in the [data viz kit](https://github.com/texastribune/data-visuals-create/pull/50#discussion_r449138570)
Then I figured it might be cool to just document some of the colors in data viz land since they'll be using this framework soon. Maybe it's overkill 🤷‍♀️ 
`npm run dev` …
=> Establish ad colors and incorporate some data visuals colors

assets/scss/6-components/site-footer/_site-footer.scss, assets/scss/6-components/site-footer/site-footer.html, docs/src/layouts/base.njk, docs/src/layouts/example-base.njk, docs/src/pages/example-modifier.njk, docs/src/pages/example.njk
Adds a new variation of the site footer to the docs with two columns on mobile instead of three
- .c-site-footer__inner--standard
- .c-site-footer__links--standard
To make our footer more mobile-friendly ([according to Google](https://web.dev/tap-targets/) 🤷‍♀️ )
The mobile layout I had to add to fix our lighthouse score is a little complicated. That got me thinking that we may just want to build it in as a variation to prevent having to copy/paste it everywhere the standard footer is used, which is a growing number of repos.
`npm run dev`
See: [The "standard" site footer](localhost:8080/modifier/c-site-footer__inner--standard/)
The donations account page footer will get a few more styles than it actually needs, but that seems fine to me. Everywhere else, we'll be able to delete some of …
=> New footer docs and mobile footer redesign

docs/src/macros/toggle-view.njk
Fixes these broken previews for "recipe" docs
None
None
Better docs
`npm run dev`
See: [kicker](http://localhost:8080/sections/typography/kicker/)
No release needed; this is a docs change only
=> Fix broken previews in docs

assets/scss/6-components/list/_list.scss, assets/scss/6-components/list/list.html, package-lock.json, package.json
Kill `c-list--arrows`
- `c-list--arrows`
Art-team recommendation. It started with cutting this style from the home-page series module and is now ending with getting rid of it entirely.
Confirm the example of `c-list` looks OK and has bullets.
This will be a minor release.
=> Remove arrow-list style

assets/scss/6-components/tabs/_tabs.scss
See title
None
None
The tabs styles assume that tabs will be `<a>` tags, but I recently implemented tabs on the republish page where we're set up to use buttons. It made me realize, we should probably force the pointer cursor as an indicator for those being clickable elements.
`npm run dev`
See: [tabs](http://localhost:8080/sections/components/c-tabs/)
Nope, just a patch IMO
=> Always give tabs a pointer cursor

assets/scss/4-elements/_all.scss, assets/scss/6-components/button/_button.scss, assets/scss/6-components/navbar/_navbar.scss, assets/scss/6-components/tabs/_tabs.scss
Makes `cursor: pointer` default on the `<button>` element
I keep finding new places where I need to add `cursor: pointer` to buttons e.g. tabs and the icon button to ascend/descend in table columns. 
As it turns out,  making all buttons have pointers is a bit of a hot take. There's [a thread](https://ux.stackexchange.com/questions/105024/why-dont-button-html-elements-have-a-css-cursor-pointer-by-default) on the internet where people argue about it, but this line won me over in favor of it:
> One of the main tenets of UX is "don't make me think" .... if you don't have a hand pointer over a button then you have to think "is this a button?"
Nothing to test really
Nope. I'm going to merge this and just let it hang out until the next release. It'll help with a forthcoming table PR which I'll …
=> Make cursor: pointer default on all button elements

assets/scss/2-tools/_mixins.scss, assets/scss/5-typography/_links.scss, assets/scss/6-components/_all.scss, assets/scss/6-components/button/_button.scss, assets/scss/6-components/button/button.html, assets/scss/6-components/tag/_tag.scss, assets/scss/6-components/tag/tag.html, assets/scss/all.scss, assets/scss/utilities/_color-helpers-parties.scss, assets/scss/utilities/_color-helpers.scss, assets/scss/utilities/_rounded.scss
- Adds a new tag component to account for our party-pills
- Cleans up some of the color helper and border-radius docs
- c-tag
- c-tag--fixed - For fixed width/height tags
- has-bg-<party> - For bg colors of ^
- is-rounded-full* - For circles
- t-links-unset* - For if tags inherit unwanted link styles
*These is the only ones that will actually show up in global CSS
Accounts for styles in the Texas lawmakers directory and maybe some data visuals projects if these could also work for them.
`npm run dev`
- [c-tag](http://localhost:8080/sections/components/c-tag/) - How do you feel about this name, @AndrewGibson27?
I did some, "what do people tend to call these" research (added below) and `tag` seemed to be the most common. It also felt handy that both the name and how it's styled meant it …
=> Scope out directory components

assets/scss/6-components/table/_table.scss, assets/scss/6-components/table/table.html, contributing.md
Right now, the class `c-table--bordered` applies a row (top/bottom) border, but this changes that to apply both row and cell (left/right) borders. 
This also documents the recommended markup for sorted column headers
-`.c-table--bordered-rows`- For case where you _just_ want row borders
Used for directory
`npm run dev`
See: [c-table](http://localhost:8080/sections/components/c-table/)
I've been sorta walking back on my initial interpretation of what merits a major release. I think instead of anything that introduces a visual _change_, it should be anything that introduces visual _disruption_. In this example, this PR will make [this `c-table--bordered` instance](https://github.com/texastribune/donations/blob/6ee8c2f81bc947b5e6276ff1f485154a5274c709/static/js/src/entry/account/components/Pa …
=> Allow for table borders on row and cells

assets/scss/6-components/text-input/_text-input.scss, assets/scss/7-layout/_position.scss, assets/scss/7-layout/position.html, assets/scss/utilities/_all.scss, assets/scss/utilities/_overflow.scss
Adds more positioning options and builds in a fix for Safari's mobile zoom bug.
- c-text-input__input--standard
- l-pos-sticky
- l-pos-top
- l-pos-front
- has-overflow-x
None removed yet, but I think these allow us to delete properties on other components.
This was part of the directory refactor. This is will increase CSS file size for now, but I think we can go back and delete a few lines of other class properties in favor of these helpers.
`npm run dev`
Not yet, we'll save the breaking changes where we remove overlapping properties in the next release. Keeping this as part of our directory pre-release.
=> Add directory utility classes

assets/scss/6-components/tabs/_tabs.scss, assets/scss/6-components/tabs/tabs.html
Updates our style base to use the [tabs we added for directory](https://www.texastribune.org/directory/)
We made the tabs more minimal for directory because it allowed us to squish them down smaller on mobile. @AndrewGibson27 also provided a model for making our tabs accessible, which has been implemented here.
`npm run dev`
See: /sections/components/c-tabs/
It does, this will have to be a major release because of the markup changes needed.
=> Add new tabs design

assets/scss/5-typography/_all.scss, assets/scss/5-typography/_copy.scss, assets/scss/6-components/list/_list.scss, assets/scss/6-components/list/list.html
- Adds a helper to achieve our single column of text layout and associated type styles
- Adds new list variations
- t-copy
- c-list--indented
- c-list--hoverable
Those names might have some room for improvement. Let me know if there are better modifiers for c-list. Naming is hard. 
The `t-copy` class helps us avoid the descendant selectors in `c-story-body` and makes it easier to add `t-copy` to any element without having to worry about its parent or whether is a p vs div etc.
The new c-list styles allow us to account for lists that live in the context of an article. Similar deal as above.
`npm run dev`
- [t-copy](http://localhost:8080/sections/typography/t-copy/)
- [c-list](http://localhost:8080/sections/components/c-list/)
It made sense for the list hover effect to be a modifier rather …
=> Add type helpers for modular text plugins

assets/scss/6-components/navbar/_navbar.scss
Removes the nested c-icon color rule in the navbar component
Setting the icon color this way makes it hard to override
`npm run dev`
See: [c-navbar](http://localhost:8080/sections/components/c-navbar/)
The implications of this is that if you accept this new version, an icon would inherit its color from its ancestor. This is a visual change shouldn't be too disruptive or "breaking" because that's likely the text color, which it's safe to assume would have enough contrast already.
Pairs with: https://github.com/texastribune/texastribune/pull/4725
=> Navbar icon update

package-lock.json, package.json
updates the docs static generator library
also runs `npm audit fix` which I meant to comment in the message of 4cec271144d20280bfa62492dcbbd68dcdaa09ab
gets rid of some security vulnerabilities
just make sure the site spins up
nope
=> Bump eleventy from 1.0.0 to 2.0.1

.vscode/settings.json, assets/scss/5-typography/_t-helpers.scss, assets/scss/5-typography/wrap.html
Adds a new helper for balancing text
- t-wrap-balance
This is becoming more [supported](https://caniuse.com/css-text-wrap-balance). Tailwind even [recently added](https://tailwindcss.com/blog/tailwindcss-v3-4#balanced-headlines-with-text-wrap-utilities) it as a helper
`npm run dev`
See: [t-wrap](http://localhost:8080/sections/typography/t-wrap-setting/)
No it's only additive. It's one more style to load but this will be an overall perf. win on our homepage for browsers that support it.
=> Add text balance helper ⚖️ 

.vscode/settings.json, assets/scss/7-layout/_align-items.scss, assets/scss/7-layout/_all.scss, assets/scss/7-layout/_flex.scss, assets/scss/7-layout/_justify-content.scss, assets/scss/7-layout/flex.html
Adds some super basic flexbox classes
- .l-flex - **display:flex** Uses flexbox.
- .l-flex-row - **flex-direction: row** Horizontal flexbox.
- .l-flex-column - **flex-direction: column** Vertical flexbox.
- .l-ai-center - **align-items: center** Center items vertically (for row).
- .l-jc-center - **justify-content: center** Center items horizontally (for row).
- .l-jc-space - **justify-content: space-between** Evenly space items horizontally (for row).
In theory, it will shave some lines from our current CSS
- display: flex - [found about 24 times](https://github.com/search?q=repo:texastribune/texastribune+display:+flex+language:SCSS&type=code&l=SCSS&p=1)
- flex-direction: row - [found about 6 times](https://github.com/search?q=repo:texastribune/texastribune+flex-direction:+row+language:SC …
=> Flexbox helpers 💪 
